# 深度学习1：张量的基本操作

### 类似 numpy 的方式初始化 torch

In [27]:
import torch as t
x = t.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
x

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [3]:
x.shape

torch.Size([3, 3, 4])

### 形状变换操作

In [4]:
y = x.reshape(4,9)
y

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12,  1,  2,  3],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12]])

### `cat` 函数执行拼接

按行合并矩阵，相当于
\begin{pmatrix}
y \\
y \\
\end{pmatrix}
按列合并矩阵，相当于
\begin{pmatrix}
y & y \\
\end{pmatrix}

In [5]:
t.cat((y,y),dim=0)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12,  1,  2,  3],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12,  1,  2,  3],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [6]:
t.cat((y,y), dim=1)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12,  1,  2,  3,  4,  5,  6, 10, 11, 12,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12,  1,  2,  3,  7,  8,  9, 10, 11, 12,  1,  2,  3],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### 广播机制
- 广播机制是指不同形状的张量之间的算术运算的执行方式。
- 即适当复制元素的行或列使得两个张量的形状相同后，再按元素运算。

### 索引
1. `:` 表示范围
2. `::` 表示步长

In [7]:
y

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12,  1,  2,  3],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [8]:
y[0:3,:]

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12,  1,  2,  3]])

In [9]:
y[:,::3]

tensor([[ 1,  4,  7],
        [10,  1,  4],
        [ 7, 10,  1],
        [ 4,  7, 10]])

### 内存管理
`id` 查看内存地址

In [10]:
x = t.arange(36).reshape((4,9))
x

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])

1. 内存指定

   观察下面的结果，发现：如果使用索引的方式，那么内存是不变的，而使用 `+` 会创建新的内存。

In [11]:
u = t.zeros_like(y)
z = t.zeros_like(y)

In [12]:
before = id(u)
u = x + y
id(u) == before

False

In [13]:
before = id(z)
z[:] = x + y
id(z) == before
# 使用这种方式就不会创建新的内存！
# 若后续不需使用y，则可以使用 y[:] = y + x 来减少内存开销

True

下面给出两种节省内存的方法：

In [14]:
Before = id(x)
x += y
id(x) == Before

True

In [15]:
Before = id(x)
t.add(x,y,out=x)
id(x) == Before

True

### Numpy 与 Tensor 的转换

In [16]:
# Tensor to Numpy (共享内存)
import numpy as np
a = t.ones(5)
b = a.numpy()
print(a, b)
a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [17]:
# Numpy to Tensor (共享内存)
a = np.ones(5)
b = t.from_numpy(a)
print(a, b)
a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [18]:
# 用 torch.tensor() 直接转换，就会创建新内存
c = t.tensor(a)
print(a, c)
a += 1
print(a, c)
c += 114
print(a, c)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([117., 117., 117., 117., 117.], dtype=torch.float64)


### 使用 GPU 计算
- `to()` 函数可以实现数据的设备转换（CPU/GPU）

In [19]:
t.cuda.is_available() and t.cpu.is_available()

True

In [20]:
device = t.device("cuda")
x.to(device)

tensor([[ 2,  5,  8, 11, 14, 17, 20, 23, 26],
        [29, 32, 35, 14, 17, 20, 23, 26, 29],
        [32, 35, 38, 41, 44, 47, 26, 29, 32],
        [35, 38, 41, 44, 47, 50, 53, 56, 59]], device='cuda:0')

In [21]:
x.to("cpu")

tensor([[ 2,  5,  8, 11, 14, 17, 20, 23, 26],
        [29, 32, 35, 14, 17, 20, 23, 26, 29],
        [32, 35, 38, 41, 44, 47, 26, 29, 32],
        [35, 38, 41, 44, 47, 50, 53, 56, 59]])

### 线性代数操作
1. 按轴求和
   
   如何理解 `axis` 这个量，可以直接从写法上理解。比如对于 
$$
\left[
\begin{array}{c}
\left[
\begin{array}{cccc}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11
\end{array}
\right] \\
\left[
\begin{array}{cccc}
12 & 13 & 14 & 15 \\
16 & 17 & 18 & 19 \\
20 & 21 & 22 & 23
\end{array}
\right]
\end{array}
\right]
$$ 
去掉最外层括号，发现是两个矩阵，这就代表 `axis=0`，去掉第一层括号，发现是三个向量，这就代表 `axis=1`，去掉第二层括号，发现是四个数，这就代表 `axis=2`。
   
因此在求和的时候，`axis = 0` 就代表去掉最外层括号，计算第一层元素的张量和。`axis = n` 就代表去掉第 `n + 1` 层括号，计算第 `n + 1` 层元素的张量和。
   


In [22]:
p = t.tensor([[1,4,6,2],
          [4,6,24,4],
          [0,9,3,8]])
print(p.sum(axis=0), p.sum(axis=1))

tensor([ 5, 19, 33, 14]) tensor([13, 38, 20])


In [23]:
q = t.arange(2*3*4).reshape(2,3,4)
q

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [24]:
for i in range(0, 3):
    print(f'axis = {i}',q.sum(axis=i))

axis = 0 tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
axis = 1 tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
axis = 2 tensor([[ 6, 22, 38],
        [54, 70, 86]])


In [25]:
for i in range(0, 3):
    print(f'axis = {i}',q.sum(axis=i,keepdims=True)) # 保留维度

axis = 0 tensor([[[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]])
axis = 1 tensor([[[12, 15, 18, 21]],

        [[48, 51, 54, 57]]])
axis = 2 tensor([[[ 6],
         [22],
         [38]],

        [[54],
         [70],
         [86]]])


2. 范数
   1. $ L_2 $ 范数：`norm(p=2)`
   2. $ L_1 $ 范数：`abs().sum()`
   3. $ Forbenius $ 范数：`norm(p='fro')`

In [26]:
matrix = t.tensor([[1.,0,0],
          [0,25,0],
          [0,0,9]])
print(t.norm(matrix, p=2))
print(t.abs((matrix).sum()))
t.norm(matrix, p='fro')

tensor(26.5895)
tensor(35.)


tensor(26.5895)