# 深度学习3.4： Softmax 回归的实现

In [2]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

### Sum 运算符回顾
若设置 `keepdim=True`，则在求和后保留维度，依然为多维张量，否则会压缩维度。

In [3]:
X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [4]:
X.sum(0), X.sum(1)

(tensor([5., 7., 9.]), tensor([ 6., 15.]))

### Softmax 函数的实现
**按行求指数和，再除以该和进行行规范化**

In [5]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdims=True)
    return X_exp / partition
softmax(X).sum(1)

tensor([1., 1.])

### 回归模型的实现
这里要做的是把每个样本都转为向量

In [6]:
num_inputs = 784
num_outputs = 10

W = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)

In [7]:
def net(X):
    return softmax(torch.matmul(X.reshape((-1, W.shape[0])), W) + b)

### 交叉熵损失函数


In [8]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]

tensor([0.1000, 0.5000])

In [ ]:
def cross_entropy(y_hat, y):
    return - torch.log(y_hat[range(len(y_hat)), y]) # range 用于生成整数序列。

cross_entropy(y_hat, y)

tensor([2.3026, 0.6931])